---
- name:
  hosts: 172.35.0.12
  become: true
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install Java 8
      apt: name=openjdk-8-jre-headless
    - name: Install net-tools
      apt: name=net-tools

- name: Download and unpack Zabbix Agent 2   installer
  hosts: 172.35.0.12
  become: true
  tasks:
  ## we'll use this for zabbix 
    - name: Download Zabbix Agent 2 
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
   