services:
  
  ansible:
    build: ./master
    container_name: ansible
    volumes:
      - ./master/hosts:/home/ansible/hosts
    networks:
      networkmain:
        ipv4_address: 172.35.0.10
  
  serveur1:
    build:
      context: ./node
    container_name: serveur1
    networks:
      networkmain:
        ipv4_address: 172.35.0.11


      
networks:
  networkmain:
    driver: bridge
    ipam:
      config:
        - subnet: 172.35.0.0/24