services:
  
  ansible:
    build: ./master
    container_name: ansible
    volumes:
      - ./master/hosts:/home/ansible/hosts
      - ./master/playbooks:/home/ansible/playbooks
    networks:
      networkmain:
        ipv4_address: 172.35.0.10
  
# group network I
  serveur1: 
    build:
      context: ./node
    container_name: serveur1
    networks:
      networkmain:
        ipv4_address: 172.35.0.11
  serveur2:
    build:
      context: ./node
    container_name: serveur2
    networks:
      networkmain:
        ipv4_address: 172.35.0.12
  serveur3:
    build:
      context: ./node
    container_name: serveur3
    networks:
      networkmain:
        ipv4_address: 172.35.0.13
              
#Network II
  bastion:
    build:
      context: ./node
    container_name: bastion
    networks:
      networkmain:
        ipv4_address: 172.35.0.14
      networksecondary:
        ipv4_address: 10.100.0.3

  serveur4:
    build:
      context: ./node
    container_name: serveur4
    networks:
      networksecondary:
        ipv4_address: 10.100.0.4

### Network

networks:
  networkmain:
    driver: bridge
    ipam:
      config:
        - subnet: 172.35.0.0/24
  networksecondary:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.0.0/24